project:
  name: hugo-deployment-pipeline
  owner: sshvans@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  cicd-test:
    parameters:
      RepoName: hugo-repo
      HostingBucketName: hugowebsitebucket
      S3BucketName: $[taskcat_autobucket]
    regions:
      - us-west-2
    s3_bucket: ''
    template: templates/master.template.yaml